version: '3.1'

services:

  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  bulktest:
    build: .
    depends_on:
      - mongo
    environment:
      REAL_MONGO_CONNECTION_STRING: "mongodb://root:example@mongo/admin"
